# 헷갈리는 문법 정리하기

## map, apply, applymap

In [52]:
import pandas as pd

data = {'a ' : [1,3,7,4],
        'b': [17,86,52,68],
        'c': [134,874,592,246]}

df1 = pd.DataFrame(data)
df1

a    b    c
0   1  17  134
1   3  86  874
2   7  52  592
3   4  68  246

### 1. map 함수
* 반드시 Series 타입에서만 사용
* Series = value + index

In [ ]:
f1 = lambda x: '%03d' %x

## * apply / asapply

In [1]:
import numpy as np

a = np.array(np.arange(20)).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [2]:
np.sum(a, axis= 0) #shape = (5,)

array([30, 34, 38, 42, 46])

In [3]:
np.sum(a, axis=0, keepdims= True) #shape= (1,5)

array([[30, 34, 38, 42, 46]])

## * array / asarray

In [18]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
arrB = np.asarray(arr) #참조본 생성
arrC= np.array(arr) #복사본 생성

In [20]:
arr[1]= np.pi
arr

array([[1.        , 1.        , 1.        , 1.        ],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [1.        , 1.        , 1.        , 1.        ]])

In [21]:
arrB #asarray은 자동으로 변경된다.

array([[1.        , 1.        , 1.        , 1.        ],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [1.        , 1.        , 1.        , 1.        ]])

In [22]:
arrC #array는 변경되지 않는다.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## * append / extend
* append :  목록 끝에 '단일 요소'로 추가한다. => 목록 자체의 길이는 1씩 증가
            개체가 숫자, 문자, 다른 목록 또는 기타 무엇이든 관계없이 끝에 추가된다.
* extend :  iterable 에서 '요소 목록'을 추가하여 목록을 확장한다. => 목록 길이는 반복 가능한 인수씩

### append

In [27]:
x = [1,2,3]
x.append([4,5])
x

[1, 2, 3, [4, 5]]

In [28]:
x.append(['very', 'good'])
x

[1, 2, 3, [4, 5], ['very', 'good']]

### extend

In [29]:
x = [1,2,3]
x.extend([4,5])
x

[1, 2, 3, 4, 5]

In [30]:
x.extend(['very', 'good'])
x

[1, 2, 3, 4, 5, 'very', 'good']

## * multiply / matmul / dot

In [42]:
a = np.array([1,2,3,4,5,6]).reshape(2,3)
b = np.array([7,8,9,10,11,12]).reshape(2,3)
print(a,'\n')
print(b, '\n')
print(b.T,)

[[1 2 3]
 [4 5 6]] 

[[ 7  8  9]
 [10 11 12]] 

[[ 7 10]
 [ 8 11]
 [ 9 12]]


### multiply: 똑같은 shape 일 때 가능

In [43]:
np.multiply(a,b)

array([[ 7, 16, 27],
       [40, 55, 72]])

### matmul: 2차원 이상일 때 (스칼라 곱셈 X)

In [45]:
np.matmul(a,b.T)

array([[ 50,  68],
       [122, 167]])

### dot: 스칼라로 곱해도 된다.

In [46]:
np.dot(a,b.T)

array([[ 50,  68],
       [122, 167]])

### tensorflow.keras로 구현(3D이어야 한다.)

## * merge
https://nittaku.tistory.com/121

In [75]:
import pandas as pd
df1 = pd.DataFrame({'data1': range(7),'key': list('bbacaab')})
df2 = pd.DataFrame({"data2": range(3),"key": list('abc')})
print(df1,'\n')
print(df2)

   data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b 

   data2 key
0      0   a
1      1   b
2      2   c


In [77]:
pd.merge(df1, df2, on = 'key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0
6      3   c      2

In [78]:
pd.merge(df1, df2, on='key', how='outer')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0
6      3   c      2

* item()
* value
* map
* counter
* pd.Series
* vstack / hstack
* iloc / loc